package es.codeurjc.squirrel.drey;

public enum HazelcastStructure {

	MAP, QUEUE, RINGBUFFER, SET, LIST, MULTI_MAP, REPLICATED_MAP, CARDINALITY_ESTIMATOR,
	TOPIC,
	LOCK, SEMAPHORE, ATOMIC_LONG, ATOMIC_REFERENCE, ID_GENERATOR, COUNTDOWN_LATCH;

}
